### ISSUE TITLE
Yarn install fails: Invalid bin entry for "пше" (in "@danakt/pshe").

### ISSUE THREAD

**Issue by KristobalJunta** [Shastel/pshe#4]
Yarn global intall for package fails. A short log is supplied below.

OS: ubuntu 19.10
yarn: 1.22.4
nodejs: 12.6.1

Although, `npm install -g @danakt/pshe` works

```
❯ yarn global add @danakt/pshe
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
warning @danakt/pshe@0.1.0: Invalid bin entry for "пше" (in "@danakt/pshe").
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "@danakt/pshe@0.1.0" has no binaries
Done in 2.94s.
```

**Comment by Shastel** [comment]
Hi @KristobalJunta, it seems that you fire the issue in for the wrong package.

I can suggest you try `yarn global add pshe`

Or fire an issue [in the correct place](https://github.com/danakt/pshe/issues)

**Comment by KristobalJunta** [comment]
Oh, excuse me. I actually filed an issue in the wrong place.
Thank you

**Comment by Shastel** [comment]
NP
